"use client";

import {useEffect, useRef, useState} from "react";
import {Award, Check, Download, Eye, Images, Layers3, LayoutTemplate, ShieldCheck, WandSparkles} from "lucide-react";

export type BrandAssetPhoto={id:string;dataUrl:string;agentName?:string;agentId?:string;agentMobile?:string;agentRenTag?:string;agentOfficePhone?:string};
type Template="subsale"|"awards";
type SubsaleDetails={name:string;mobile:string;ren:string;officePhone:string};

export default function BrandAssetStudio({photos,onOpenPhotos,onToast}:{photos:BrandAssetPhoto[];onOpenPhotos:()=>void;onToast:(message:string)=>void}){
 const [selectedId,setSelectedId]=useState(photos[0]?.id??""),[template,setTemplate]=useState<Template>("subsale"),[cutout,setCutout]=useState(""),[removing,setRemoving]=useState(Boolean(photos[0])),[exporting,setExporting]=useState(false),[name,setName]=useState(photos[0]?.agentName||"AGENT NAME"),[award,setAward]=useState("Top Producer 2026"),[scale,setScale]=useState(90),[position,setPosition]=useState(0);
 const previewRef=useRef<HTMLDivElement>(null);
 const photo=photos.find(item=>item.id===selectedId)??photos[0],portrait=cutout||(template==="awards"?photo?.dataUrl:"")||"",subsaleDetails=getSubsaleDetails(photo,name),hasAtlasDetails=Boolean(photo?.agentMobile&&photo?.agentRenTag&&photo?.agentName&&photo.agentName!=="Walk-in");
 const choosePhoto=(next:BrandAssetPhoto)=>{setSelectedId(next.id);setCutout("");setRemoving(true);setName(next.agentName||"AGENT NAME")};
 const removeBackground=async()=>{if(!photo||removing)return;setRemoving(true);try{setCutout(await createPortraitCutout(photo.dataUrl));onToast("AI background removed")}catch{onToast("Background removal could not finish. Try another photo.")}finally{setRemoving(false)}};
 const exportBanner=async()=>{if(!cutout||!hasAtlasDetails||exporting)return;setExporting(true);try{const result=await renderSubsaleBanner(cutout,{scale,position,details:subsaleDetails}),link=document.createElement("a");link.href=result;link.download=`${safeName(name)}-subsale-banner.png`;document.body.appendChild(link);link.click();link.remove();onToast("Subsale banner downloaded with Atlas details")}catch{onToast("The banner file could not be prepared.")}finally{setExporting(false)}};
 const previewFullscreen=async()=>{try{await previewRef.current?.requestFullscreen()}catch{onToast("Full-screen preview is not available in this browser.")}};
 useEffect(()=>{if(!photo?.dataUrl)return;let active=true;createPortraitCutout(photo.dataUrl).then(result=>{if(active)setCutout(result)}).catch(()=>{if(active)onToast("Background removal could not finish. Choose another portrait or retry.")}).finally(()=>{if(active)setRemoving(false)});return()=>{active=false}},[photo?.dataUrl,onToast]);
 if(!photo)return <section className="asset-empty"><span><Images size={28}/></span><h1>Create brand assets</h1><p>Save or import a portrait first. Your approved photo can then be placed into designer-supplied templates.</p><button type="button" onClick={onOpenPhotos}>Open Photos</button></section>;
 return <section className="asset-studio">
  <header className="asset-header"><div><span className="eyebrow">DESIGNER TEMPLATES</span><h1>Place your portrait. Keep the brand intact.</h1><p>Choose a designer-supplied format, apply the automatic cutout, and export without changing the locked artwork.</p></div><span className="asset-local"><ShieldCheck size={15}/> Local &amp; private</span></header>
  <div className="asset-layout">
   <aside className="asset-controls">
    <section className="asset-control-group"><div className="asset-group-title"><span>01</span><div><b>Choose portrait</b><small>Approved photos</small></div></div><div className="asset-photo-list" role="list">{photos.map(item=><button type="button" className={item.id===photo.id?"active":""} onClick={()=>choosePhoto(item)} aria-pressed={item.id===photo.id} key={item.id}><img src={item.dataUrl} alt={item.agentName||"Saved portrait"} width={58} height={72}/>{item.id===photo.id?<i><Check size={13}/></i>:null}</button>)}</div></section>
    <section className="asset-control-group"><div className="asset-group-title"><span>02</span><div><b>Background removal</b><small>Required for this template</small></div></div><button type="button" className={`asset-ai-button ${cutout?"done":""}`} onClick={()=>void removeBackground()} disabled={removing}>{cutout?<Check size={18}/>:<WandSparkles size={18}/>}<span><b>{removing?"Removing background…":cutout?"Background removed":"Retry background removal"}</b><small>{cutout?"Transparent portrait applied automatically":"Nothing exports until this is ready"}</small></span></button></section>
    <section className="asset-control-group"><div className="asset-group-title"><span>03</span><div><b>{template==="subsale"?"Atlas information":"Event details"}</b><small>{template==="subsale"?"Filled from the agent profile":"Editable fields"}</small></div></div>{template==="awards"?<><label className="asset-field"><span>Name</span><input value={name} onChange={event=>setName(event.target.value.toUpperCase())} maxLength={32}/></label><label className="asset-field"><span>Award</span><input value={award} onChange={event=>setAward(event.target.value)} maxLength={46}/></label></>:<><p className="asset-template-note">The layout follows the approved 3 × 2 For Sale board. Agent details come from the Atlas appointment.</p><dl className="asset-atlas-info"><div><dt>Mobile</dt><dd>{subsaleDetails.mobile}</dd></div><div><dt>Name</dt><dd>{subsaleDetails.name}</dd></div><div><dt>REN</dt><dd>{subsaleDetails.ren}</dd></div><div><dt>Office</dt><dd>{subsaleDetails.officePhone}</dd></div></dl></>}<div className="asset-range"><span><label htmlFor="asset-portrait-size">Portrait size</label><output>{scale}%</output></span><input id="asset-portrait-size" type="range" min="80" max="130" value={scale} onChange={event=>setScale(Number(event.target.value))}/></div><div className="asset-range"><span><label htmlFor="asset-portrait-position">Vertical position</label><output>{position}</output></span><input id="asset-portrait-position" type="range" min="-20" max="20" value={position} onChange={event=>setPosition(Number(event.target.value))}/></div></section>
   </aside>
   <div className="asset-workbench">
    <div className="asset-tabs" aria-label="Designer template"><button type="button" className={template==="subsale"?"active":""} onClick={()=>setTemplate("subsale")} aria-pressed={template==="subsale"}><LayoutTemplate size={17}/><span><b>Subsale banner</b><small>Designer artwork · Print ready</small></span></button><button type="button" className={template==="awards"?"active":""} onClick={()=>setTemplate("awards")} aria-pressed={template==="awards"}><Award size={17}/><span><b>Awards night</b><small>16:9 · Preview</small></span></button></div>
    <div className="designer-lock"><Layers3 size={15}/><span><b>Designer artwork</b> Logo, colours and layout are locked</span></div>
    <div ref={previewRef} className={`asset-preview-shell ${template}`}>{template==="subsale"?<SubsaleBannerPreview portrait={portrait} details={subsaleDetails} scale={scale} position={position} cutout={Boolean(cutout)}/>:<AwardsPreview portrait={portrait} name={name} award={award} scale={scale} position={position} cutout={Boolean(cutout)}/>}</div>
    {template==="subsale"?<div className={`asset-export-bar ${hasAtlasDetails?"":"missing-atlas"}`}><div><span><Check size={16}/>{hasAtlasDetails?"Designer template and Atlas details applied":"Atlas details required"}</span><small>{hasAtlasDetails?"2650 × 1786 PNG · transparent agent portrait":"Book through Atlas so mobile and REN information follow the portrait"}</small></div><button type="button" onClick={()=>void exportBanner()} disabled={exporting||!cutout||!hasAtlasDetails}><Download size={18}/>{removing?"Removing background…":exporting?"Preparing…":hasAtlasDetails?"Download banner":"Atlas details required"}</button></div>:<div className="asset-preview-bar"><div><span><Eye size={16}/> Preview only</span><small>16:9 screen mockup · Nothing will be downloaded</small></div><button type="button" onClick={()=>void previewFullscreen()}><Eye size={17}/> Preview full screen</button></div>}
   </div>
  </div>
 </section>;
}

function SubsaleBannerPreview({portrait,details,scale,position,cutout}:{portrait:string;details:SubsaleDetails;scale:number;position:number;cutout:boolean}){return <div className={`subsale-banner-preview ${cutout?"has-cutout":""}`}><img className="subsale-artwork" src="/subsale-banner-template.png" alt="IQI For Sale designer banner template" width={2650} height={1786}/><strong className="subsale-mobile">{details.mobile}</strong><div className="subsale-agent-line"><strong style={{fontSize:`${previewNameSize(details.name)}cqw`}}>{details.name}</strong><span>{details.ren}</span></div><strong className="subsale-office-phone">{details.officePhone}</strong><div className="subsale-photo">{portrait?<img src={portrait} alt="Agent portrait with background removed" width={960} height={1200} style={{transform:`translateY(${position}%) scale(${scale/100})`}}/>:<span><WandSparkles size={22}/> Removing background…</span>}</div></div>}

function AwardsPreview({portrait,name,award,scale,position,cutout}:{portrait:string;name:string;award:string;scale:number;position:number;cutout:boolean}){return <div className={`awards-preview ${cutout?"has-cutout":""}`}><div className="awards-beam one"/><div className="awards-beam two"/><div className="awards-copy"><span>STUDIO+ AWARDS NIGHT · 2026</span><Award size={30}/><small>CELEBRATING EXCELLENCE</small><h2>{name||"Agent Name"}</h2><p>{award||"Top Producer 2026"}</p></div><div className="awards-photo"><img src={portrait} alt="Awards night screen portrait preview" width={960} height={1200} style={{transform:`translateY(${position}%) scale(${scale/100})`}}/></div><div className="awards-footer"><span>STUDIO+</span><i/><b>YOUR SUCCESS. OUR PRIDE.</b></div></div>}

async function createPortraitCutout(src:string){
 const image=await loadAssetImage(src),vision=await import("@mediapipe/tasks-vision"),files=await vision.FilesetResolver.forVisionTasks("/mediapipe"),segmenter=await vision.ImageSegmenter.createFromOptions(files,{baseOptions:{modelAssetPath:"/selfie_segmenter.tflite"},runningMode:"IMAGE",outputConfidenceMasks:true,outputCategoryMask:false});
 try{const result=segmenter.segment(image);try{const mask=result.confidenceMasks?.[0];if(!mask)throw new Error("No person mask");const values=mask.getAsFloat32Array(),maskCanvas=document.createElement("canvas"),maskContext=maskCanvas.getContext("2d"),output=document.createElement("canvas"),context=output.getContext("2d");maskCanvas.width=mask.width;maskCanvas.height=mask.height;output.width=image.naturalWidth;output.height=image.naturalHeight;if(!maskContext||!context)throw new Error("Canvas unavailable");const pixels=maskContext.createImageData(mask.width,mask.height);for(let index=0;index<values.length;index++){const confidence=Math.max(0,Math.min(1,(values[index]-.04)/.78)),soft=confidence*confidence*(3-2*confidence),offset=index*4;pixels.data[offset]=255;pixels.data[offset+1]=255;pixels.data[offset+2]=255;pixels.data[offset+3]=Math.round(soft*255)}maskContext.putImageData(pixels,0,0);context.drawImage(image,0,0,output.width,output.height);context.globalCompositeOperation="destination-in";context.imageSmoothingEnabled=true;context.imageSmoothingQuality="high";context.drawImage(maskCanvas,0,0,output.width,output.height);const bounds=findPersonBounds(values,mask.width,mask.height);if(!bounds)throw new Error("No person detected");return cropCutoutToPerson(output,{...bounds,maskWidth:mask.width,maskHeight:mask.height}).toDataURL("image/png")}finally{result.close()}}finally{segmenter.close()}
}

function findPersonBounds(values:Float32Array,width:number,height:number){const columns=new Uint16Array(width),rows=new Uint16Array(height);for(let index=0;index<values.length;index++){if(values[index]<.45)continue;const x=index%width,y=Math.floor(index/width);columns[x]++;rows[y]++}const columnMinimum=Math.max(2,Math.floor(height*.018)),rowMinimum=Math.max(2,Math.floor(width*.018)),minX=columns.findIndex(count=>count>=columnMinimum),minY=rows.findIndex(count=>count>=rowMinimum);let maxX=-1,maxY=-1;for(let x=width-1;x>=0;x--){if(columns[x]>=columnMinimum){maxX=x;break}}for(let y=height-1;y>=0;y--){if(rows[y]>=rowMinimum){maxY=y;break}}return minX<0||minY<0||maxX<minX||maxY<minY?null:{minX,minY,maxX,maxY}}

function cropCutoutToPerson(source:HTMLCanvasElement,bounds:{minX:number;minY:number;maxX:number;maxY:number;maskWidth:number;maskHeight:number}){const scaleX=source.width/bounds.maskWidth,scaleY=source.height/bounds.maskHeight,subjectLeft=bounds.minX*scaleX,subjectTop=bounds.minY*scaleY,subjectRight=(bounds.maxX+1)*scaleX,subjectBottom=(bounds.maxY+1)*scaleY,subjectWidth=subjectRight-subjectLeft,subjectHeight=subjectBottom-subjectTop,padX=Math.max(source.width*.04,subjectWidth*.18),padTop=Math.max(source.height*.03,subjectHeight*.08),padBottom=Math.max(source.height*.02,subjectHeight*.05),left=Math.max(0,Math.floor(subjectLeft-padX)),top=Math.max(0,Math.floor(subjectTop-padTop)),right=Math.min(source.width,Math.ceil(subjectRight+padX)),bottom=Math.min(source.height,Math.ceil(subjectBottom+padBottom)),width=right-left,height=bottom-top;if(width<2||height<2)return source;const cropped=document.createElement("canvas"),context=cropped.getContext("2d");cropped.width=width;cropped.height=height;if(!context)return source;context.drawImage(source,left,top,width,height,0,0,width,height);return cropped}

function loadAssetImage(src:string){return new Promise<HTMLImageElement>((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=reject;image.src=src})}
function safeName(value:string){return(value.trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"studio-agent")}
function formatAtlasPhone(value:string|undefined,fallback:string){const raw=value?.trim();if(!raw||raw.toLowerCase()==="not provided")return fallback;let digits=raw.replace(/\D/g,"");if(digits.startsWith("60"))digits=`0${digits.slice(2)}`;if(/^01\d{8}$/.test(digits))return `${digits.slice(0,3)}-${digits.slice(3,6)} ${digits.slice(6)}`;if(/^011\d{8}$/.test(digits))return `${digits.slice(0,3)}-${digits.slice(3,7)} ${digits.slice(7)}`;if(/^0[2-9]\d{8}$/.test(digits))return `${digits.slice(0,2)}-${digits.slice(2,6)} ${digits.slice(6)}`;return raw}
function formatRen(value:string|undefined){const ren=value?.replace(/^REN\s*(?:NO\.?\s*:?)?\s*/i,"").trim();return `(REN No.: ${ren||"NOT SET"})`}
function getSubsaleDetails(photo:BrandAssetPhoto|undefined,name:string):SubsaleDetails{return{name:photo?.agentName||name||"AGENT NAME",mobile:formatAtlasPhone(photo?.agentMobile,"—"),ren:formatRen(photo?.agentRenTag),officePhone:formatAtlasPhone(photo?.agentOfficePhone,"03-7453 5155")}}
function previewNameSize(value:string){return Math.max(4.7,Math.min(7.5,112/Math.max(15,value.length)))}
function fitPortraitBottom(image:HTMLImageElement,width:number,height:number,scale:number,position:number){const base=Math.min(width/image.naturalWidth,height/image.naturalHeight)*scale/100,w=image.naturalWidth*base,h=image.naturalHeight*base;return{x:(width-w)/2,y:height-h+height*position/100,width:w,height:h}}

function fittedCanvasText(context:CanvasRenderingContext2D,text:string,x:number,baseline:number,maxWidth:number,fontSize:number,color:string,weight=700){const family='"DIN Alternate","Avenir Next Condensed","Arial Narrow",Arial,sans-serif';let size=fontSize;context.font=`${weight} ${size}px ${family}`;while(size>42&&context.measureText(text).width>maxWidth){size-=4;context.font=`${weight} ${size}px ${family}`}context.fillStyle=color;context.fillText(text,x,baseline);return context.measureText(text).width}
function drawSubsaleDetails(context:CanvasRenderingContext2D,details:SubsaleDetails){context.textBaseline="alphabetic";fittedCanvasText(context,details.mobile,72,1080,1980,472,"#231f20",800);context.font='700 84px "DIN Alternate","Avenir Next Condensed","Arial Narrow",Arial,sans-serif';const renWidth=context.measureText(details.ren).width,nameWidth=fittedCanvasText(context,details.name,72,1370,Math.max(620,1690-renWidth),210,"#332f30",700);fittedCanvasText(context,details.ren,72+nameWidth+34,1370,Math.max(420,1680-nameWidth),84,"#332f30",700);fittedCanvasText(context,details.officePhone,350,1720,1100,172,"#fff",700)}

async function renderSubsaleBanner(src:string,options:{scale:number;position:number;details:SubsaleDetails}){const [template,image]=await Promise.all([loadAssetImage("/subsale-banner-template.png"),loadAssetImage(src)]),canvas=document.createElement("canvas"),context=canvas.getContext("2d"),width=2650,height=1786;canvas.width=width;canvas.height=height;if(!context)throw new Error("Canvas unavailable");context.fillStyle="#fff";context.fillRect(0,0,width,height);context.drawImage(template,0,0,width,height);drawSubsaleDetails(context,options.details);context.save();context.beginPath();context.rect(1800,590,850,1196);context.clip();const portrait=fitPortraitBottom(image,850,1196,options.scale,options.position);context.drawImage(image,1800+portrait.x,590+portrait.y,portrait.width,portrait.height);context.restore();return canvas.toDataURL("image/png")}
