"use client";

import {useRef, useState} from "react";
import {Award, BriefcaseBusiness, Check, CreditCard, Download, Eraser, Eye, Images, LockKeyhole, Printer, ShieldCheck, WandSparkles, X} from "lucide-react";

export type BrandAssetPhoto={id:string;dataUrl:string;agentName?:string;agentId?:string};
type Template="business"|"awards";
type PrintQuantity=100|250|500;
type PrintFinish="matte"|"gloss";
const PRINT_OPTIONS:{quantity:PrintQuantity;price:number}[]=[{quantity:100,price:49},{quantity:250,price:89},{quantity:500,price:149}];

export default function BrandAssetStudio({photos,onOpenPhotos,onToast}:{photos:BrandAssetPhoto[];onOpenPhotos:()=>void;onToast:(message:string)=>void}){
 const [selectedId,setSelectedId]=useState(photos[0]?.id??""),[template,setTemplate]=useState<Template>("business"),[cutout,setCutout]=useState(""),[removing,setRemoving]=useState(false),[exporting,setExporting]=useState(false),[showCheckout,setShowCheckout]=useState(false),[printQuantity,setPrintQuantity]=useState<PrintQuantity>(100),[printFinish,setPrintFinish]=useState<PrintFinish>("matte"),[paidFor,setPaidFor]=useState(""),[name,setName]=useState(photos[0]?.agentName||"Agent Name"),[role,setRole]=useState("Property Consultant"),[phone,setPhone]=useState("+60 12 345 6789"),[email,setEmail]=useState("hello@iqiglobal.com"),[award,setAward]=useState("Top Producer 2026"),[scale,setScale]=useState(100),[position,setPosition]=useState(0);
 const previewRef=useRef<HTMLDivElement>(null);
 const photo=photos.find(item=>item.id===selectedId)??photos[0],portrait=cutout||photo?.dataUrl||"";
 const printOption=PRINT_OPTIONS.find(option=>option.quantity===printQuantity)??PRINT_OPTIONS[0],printKey=`${printQuantity}:${printFinish}`,printUnlocked=paidFor===printKey;
 const choosePhoto=(next:BrandAssetPhoto)=>{setSelectedId(next.id);setCutout("");setName(next.agentName||"Agent Name")};
 const removeBackground=async()=>{if(!photo||removing)return;setRemoving(true);try{setCutout(await createPortraitCutout(photo.dataUrl));onToast("AI background removed") }catch{onToast("Background removal could not finish. Try another photo.")}finally{setRemoving(false)}};
 const exportPrintFile=async()=>{if(!portrait||exporting||!printUnlocked)return;setExporting(true);try{const result=await renderBusinessCard(portrait,{name,role,phone,email,scale,position,cutout:Boolean(cutout)}),link=document.createElement("a");link.href=result;link.download=`${safeName(name)}-business-card-print-1050x600.png`;document.body.appendChild(link);link.click();link.remove();onToast("Print-ready business card downloaded")}catch{onToast("The print file could not be prepared.")}finally{setExporting(false)}};
 const previewFullscreen=async()=>{try{await previewRef.current?.requestFullscreen()}catch{onToast("Full-screen preview is not available in this browser.")}};
 const completeDemoPayment=()=>{setPaidFor(printKey);setShowCheckout(false);onToast("Demo payment approved — print file unlocked")};
 if(!photo)return <section className="asset-empty"><span><Images size={28}/></span><h1>Create brand assets</h1><p>Save or import a portrait first, then turn it into event and business artwork.</p><button type="button" onClick={onOpenPhotos}>Open Photos</button></section>;
 return <section className="asset-studio">
  <header className="asset-header"><div><span className="eyebrow">CREATE &amp; PREVIEW</span><h1>One portrait. Two useful formats.</h1><p>Create a print-ready business card or preview your portrait on an awards-night screen.</p></div><span className="asset-local"><ShieldCheck size={15}/> Local &amp; private</span></header>
  <div className="asset-layout">
   <aside className="asset-controls">
    <section className="asset-control-group"><div className="asset-group-title"><span>01</span><div><b>Choose portrait</b><small>From Photos</small></div></div><div className="asset-photo-list" role="list">{photos.map(item=><button type="button" className={item.id===photo.id?"active":""} onClick={()=>choosePhoto(item)} aria-pressed={item.id===photo.id} key={item.id}><img src={item.dataUrl} alt={item.agentName||"Saved portrait"} width={58} height={72}/>{item.id===photo.id?<i><Check size={13}/></i>:null}</button>)}</div></section>
    <section className="asset-control-group"><div className="asset-group-title"><span>02</span><div><b>AI background</b><small>Portrait segmentation</small></div></div><button type="button" className={`asset-ai-button ${cutout?"done":""}`} onClick={()=>void removeBackground()} disabled={removing}>{cutout?<Check size={18}/>:<WandSparkles size={18}/>}<span><b>{removing?"Removing background…":cutout?"Background removed":"Remove background"}</b><small>{cutout?"Transparent PNG ready":"Runs on this device"}</small></span></button>{cutout?<button type="button" className="asset-use-original" onClick={()=>setCutout("")}><Eraser size={15}/> Use original background</button>:null}</section>
    <section className="asset-control-group"><div className="asset-group-title"><span>03</span><div><b>Edit details</b><small>Template text and portrait</small></div></div><label className="asset-field"><span>Name</span><input value={name} onChange={event=>setName(event.target.value)} maxLength={36}/></label>{template==="business"?<><label className="asset-field"><span>Job title</span><input value={role} onChange={event=>setRole(event.target.value)} maxLength={44}/></label><label className="asset-field"><span>Phone</span><input value={phone} onChange={event=>setPhone(event.target.value)} maxLength={28}/></label><label className="asset-field"><span>Email</span><input type="email" value={email} onChange={event=>setEmail(event.target.value)} maxLength={48}/></label></>:<label className="asset-field"><span>Award</span><input value={award} onChange={event=>setAward(event.target.value)} maxLength={46}/></label>}<div className="asset-range"><span><label htmlFor="asset-portrait-size">Portrait size</label><output>{scale}%</output></span><input id="asset-portrait-size" type="range" min="80" max="130" value={scale} onChange={event=>setScale(Number(event.target.value))}/></div><div className="asset-range"><span><label htmlFor="asset-portrait-position">Vertical position</label><output>{position}</output></span><input id="asset-portrait-position" type="range" min="-20" max="20" value={position} onChange={event=>setPosition(Number(event.target.value))}/></div></section>
   </aside>
   <div className="asset-workbench">
    <div className="asset-tabs" aria-label="Asset type"><button type="button" className={template==="business"?"active":""} onClick={()=>setTemplate("business")} aria-pressed={template==="business"}><BriefcaseBusiness size={17}/><span><b>Business card</b><small>Create &amp; print</small></span></button><button type="button" className={template==="awards"?"active":""} onClick={()=>setTemplate("awards")} aria-pressed={template==="awards"}><Award size={17}/><span><b>Awards night</b><small>Preview only</small></span></button></div>
    <div ref={previewRef} className={`asset-preview-shell ${template}`}>
     {template==="business"?<BusinessCardPreview portrait={portrait} name={name} role={role} phone={phone} email={email} scale={scale} position={position} cutout={Boolean(cutout)}/>:<AwardsPreview portrait={portrait} name={name} award={award} scale={scale} position={position} cutout={Boolean(cutout)}/>} 
    </div>
    {template==="business"?<div className="asset-commerce-bar"><div className="asset-print-options"><label><span>Quantity</span><select value={printQuantity} onChange={event=>setPrintQuantity(Number(event.target.value) as PrintQuantity)}>{PRINT_OPTIONS.map(option=><option value={option.quantity} key={option.quantity}>{option.quantity} cards</option>)}</select></label><label><span>Finish</span><select value={printFinish} onChange={event=>setPrintFinish(event.target.value as PrintFinish)}><option value="matte">Premium matte</option><option value="gloss">Gloss</option></select></label></div><div className="asset-purchase"><span><small>Print-ready · 1050 × 600 PNG</small><strong>RM {printOption.price}.00</strong></span>{printUnlocked?<button type="button" onClick={()=>void exportPrintFile()} disabled={exporting}><Download size={18}/>{exporting?"Preparing…":"Download print file"}</button>:<button type="button" onClick={()=>setShowCheckout(true)}><LockKeyhole size={17}/>Pay &amp; unlock print</button>}</div></div>:<div className="asset-preview-bar"><div><span><Eye size={16}/> Preview only</span><small>16:9 screen mockup · Nothing will be downloaded</small></div><button type="button" onClick={()=>void previewFullscreen()}><Eye size={17}/> Preview full screen</button></div>}
   </div>
  </div>
  {showCheckout?<div className="asset-checkout-backdrop"><div className="asset-checkout" role="dialog" aria-modal="true" aria-labelledby="asset-checkout-title"><button type="button" className="asset-checkout-close" aria-label="Close checkout" onClick={()=>setShowCheckout(false)}><X size={18}/></button><span className="asset-checkout-icon"><Printer size={25}/></span><small>DEMO CHECKOUT</small><h2 id="asset-checkout-title">Print your business cards</h2><p>Payment unlocks the print-ready file for this order configuration.</p><div className="asset-order-summary"><span><b>{printQuantity} business cards</b><small>{printFinish==="matte"?"Premium matte":"Gloss"} · 3.5 × 2 in</small></span><strong>RM {printOption.price}.00</strong></div><div className="asset-payment-note"><ShieldCheck size={17}/><span><b>No real payment will be collected</b><small>Connect a payment provider before production use.</small></span></div><button type="button" className="asset-pay-button" onClick={completeDemoPayment}><CreditCard size={18}/>Confirm demo payment · RM {printOption.price}.00</button></div></div>:null}
 </section>;
}

function BusinessCardPreview({portrait,name,role,phone,email,scale,position,cutout}:{portrait:string;name:string;role:string;phone:string;email:string;scale:number;position:number;cutout:boolean}){return <div className={`business-card-preview ${cutout?"has-cutout":""}`}><div className="business-copy"><span className="asset-iqi">Studio+</span><small>PROFESSIONAL PORTRAITS</small><div><h2>{name||"Agent Name"}</h2><p>{role||"Property Consultant"}</p></div><ul><li>{phone||"+60 12 345 6789"}</li><li>{email||"hello@example.com"}</li><li>studio-plus.example</li></ul></div><div className="business-photo"><img src={portrait} alt="Business card portrait preview" width={960} height={1200} style={{transform:`translateY(${position}%) scale(${scale/100})`}}/></div><span className="business-accent"/></div>}

function AwardsPreview({portrait,name,award,scale,position,cutout}:{portrait:string;name:string;award:string;scale:number;position:number;cutout:boolean}){return <div className={`awards-preview ${cutout?"has-cutout":""}`}><div className="awards-beam one"/><div className="awards-beam two"/><div className="awards-copy"><span>STUDIO+ AWARDS NIGHT · 2026</span><Award size={30}/><small>CELEBRATING EXCELLENCE</small><h2>{name||"Agent Name"}</h2><p>{award||"Top Producer 2026"}</p></div><div className="awards-photo"><img src={portrait} alt="Awards night screen portrait preview" width={960} height={1200} style={{transform:`translateY(${position}%) scale(${scale/100})`}}/></div><div className="awards-footer"><span>STUDIO+</span><i/><b>YOUR SUCCESS. OUR PRIDE.</b></div></div>}

async function createPortraitCutout(src:string){
 const image=await loadAssetImage(src),vision=await import("@mediapipe/tasks-vision"),files=await vision.FilesetResolver.forVisionTasks("/mediapipe"),segmenter=await vision.ImageSegmenter.createFromOptions(files,{baseOptions:{modelAssetPath:"/selfie_segmenter.tflite"},runningMode:"IMAGE",outputConfidenceMasks:true,outputCategoryMask:false});
 try{const result=segmenter.segment(image);try{const mask=result.confidenceMasks?.[0];if(!mask)throw new Error("No person mask");const values=mask.getAsFloat32Array(),maskCanvas=document.createElement("canvas"),maskContext=maskCanvas.getContext("2d"),output=document.createElement("canvas"),context=output.getContext("2d");maskCanvas.width=mask.width;maskCanvas.height=mask.height;output.width=image.naturalWidth;output.height=image.naturalHeight;if(!maskContext||!context)throw new Error("Canvas unavailable");const pixels=maskContext.createImageData(mask.width,mask.height);for(let index=0;index<values.length;index++){const confidence=Math.max(0,Math.min(1,(values[index]-.12)/.7)),soft=confidence*confidence*(3-2*confidence),offset=index*4;pixels.data[offset]=255;pixels.data[offset+1]=255;pixels.data[offset+2]=255;pixels.data[offset+3]=Math.round(soft*255)}maskContext.putImageData(pixels,0,0);context.drawImage(image,0,0,output.width,output.height);context.globalCompositeOperation="destination-in";context.imageSmoothingEnabled=true;context.imageSmoothingQuality="high";context.drawImage(maskCanvas,0,0,output.width,output.height);return output.toDataURL("image/png")}finally{result.close()}}finally{segmenter.close()}
}

function loadAssetImage(src:string){return new Promise<HTMLImageElement>((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=reject;image.src=src})}
function safeName(value:string){return(value.trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"studio-agent")}
function fitPortrait(image:HTMLImageElement,width:number,height:number,scale:number,position:number){const base=Math.max(width/image.naturalWidth,height/image.naturalHeight)*scale/100,w=image.naturalWidth*base,h=image.naturalHeight*base;return{x:(width-w)/2,y:(height-h)/2+height*position/100,width:w,height:h}}

async function renderBusinessCard(src:string,options:{name:string;role:string;phone:string;email:string;scale:number;position:number;cutout:boolean}){const image=await loadAssetImage(src),canvas=document.createElement("canvas"),context=canvas.getContext("2d");canvas.width=1050;canvas.height=600;if(!context)throw new Error("Canvas unavailable");context.fillStyle="#f6f3ed";context.fillRect(0,0,1050,600);context.fillStyle="#17372d";context.fillRect(0,0,28,600);context.fillStyle="#17372d";context.font="800 54px Arial";context.fillText("Studio+",72,92);context.fillStyle="#9c7a42";context.font="700 14px Arial";context.letterSpacing="3px";context.fillText("PROFESSIONAL PORTRAITS",74,122);context.fillStyle="#17211d";context.font="700 45px Arial";context.fillText(options.name||"Agent Name",72,310,520);context.fillStyle="#52605a";context.font="500 22px Arial";context.fillText(options.role||"Property Consultant",74,348,510);context.fillStyle="#17211d";context.font="600 17px Arial";context.fillText(options.phone||"+60 12 345 6789",74,462,490);context.fillText(options.email||"hello@example.com",74,493,490);context.fillText("studio-plus.example",74,524);context.save();context.beginPath();context.rect(610,0,440,600);context.clip();if(!options.cutout){const box=fitPortrait(image,440,600,options.scale,options.position);context.drawImage(image,610+box.x,box.y,box.width,box.height)}else{const box=fitPortrait(image,500,620,options.scale,options.position);context.drawImage(image,585+box.x,box.y,box.width,box.height)}context.restore();context.fillStyle="#e96743";context.fillRect(1028,0,22,600);return canvas.toDataURL("image/png")}
