"use client";

import { ChangeEvent, useEffect, useMemo, useRef, useState } from "react";
import { ArrowRight, Building2, Camera, Check, CreditCard, Download, HelpCircle, Home, Images, Keyboard, MonitorCog, Printer, QrCode, RotateCcw, ScanLine, Sparkles, Trash2, Upload } from "lucide-react";
import {BrowserQRCodeReader, IScannerControls} from "@zxing/browser";

type View = "profile"|"session"|"capture"|"batch"|"review"|"select"|"consent"|"success"|"personal"|"brand"|"console";
type Assessment = { score:number; status:"pass"|"retake"; note:string; lighting:string; resolution:string };
type Photo = { id:string; dataUrl:string; createdAt:string; enhanced:boolean; profileOK:boolean; brandOK:boolean; width:number; height:number };

const nav=[{id:"profile" as View,label:"Home",icon:Home},{id:"personal" as View,label:"My photos",icon:Images},{id:"brand" as View,label:"Brand assets",icon:Building2},{id:"console" as View,label:"Studio",icon:MonitorCog}];

const Placeholder=({n=2,badge}:{n?:number;badge?:string})=><div className={`portrait p${n}`}>{badge?<span className="badge"><Check size={14}/> {badge}</span>:null}</div>;
const PhotoView=({src,className="",alt="Portrait",badge}:{src?:string;className?:string;alt?:string;badge?:string})=>src?<div className="photo-media"><img className={`user-photo ${className}`} src={src} alt={alt}/>{badge?<span className="badge"><Check size={14}/> {badge}</span>:null}</div>:<Placeholder badge={badge}/>;

function SessionProfile({agent,code,onStart}:{agent:{agentName:string;agentId:string;agentPhoto?:string;rating?:number};code:string;onStart:()=>void}){
 const [format,setFormat]=useState<"square"|"portrait">("square"),[sourceRatio,setSourceRatio]=useState(.8),[showAssessment,setShowAssessment]=useState(false);const src=agent.agentPhoto||"/api/atlas-avatar?slug=aaron-paul",target=format==="square"?1:.8;useEffect(()=>{const img=new Image();img.onload=()=>setSourceRatio(img.naturalWidth/img.naturalHeight);img.src=src},[src]);const loss=sourceRatio>target?Math.round((1-target/sourceRatio)*100):Math.round((1-sourceRatio/target)*100),direction=sourceRatio>target?"left and right sides":"top and bottom",rating=agent.rating??37;return <main className="session-profile-check"><header><span className="eyebrow">ATLAS SESSION LOADED</span><code>{code}</code></header><div className="session-profile-grid"><section className="crop-workbench"><div className="format-tabs"><button className={format==="square"?"active":""} onClick={()=>setFormat("square")}>1:1 Square</button><button className={format==="portrait"?"active":""} onClick={()=>setFormat("portrait")}>4:5 Portrait</button></div><div className={`crop-preview ${format}`}><img src={src} alt={`${agent.agentName} ${format} crop preview`}/><span className="bleed-border"/><span className="face-safe">SAFE AREA</span></div><div className={`crop-warning ${loss>12?"warn":"good"}`}><HelpCircle size={18}/><div><b>{loss>12?"This crop may feel too tight":"Crop has usable breathing room"}</b><span>{loss}% of the source is hidden from the {direction}. Keep the face and shoulders inside the dashed safe area.</span></div></div></section><section className="session-quality"><span className="eyebrow">CURRENT PROFILE</span><h1>{agent.agentName}</h1><p>Agent ID {agent.agentId}</p><button className="agent-rating" onClick={()=>setShowAssessment(v=>!v)}><strong>{rating}</strong><span>Professional photo rating<small>View assessment</small></span><ArrowRight size={17}/></button>{showAssessment?<div className="inline-assessment"><div><span>Resolution</span><b>{rating>=70?"Good":"Needs improvement"}</b></div><div><span>Framing</span><b>{loss>12?"Too tight":"Good"}</b></div><div><span>Crop loss</span><b>{loss}%</b></div><div><span>Safe area</span><b>{loss>20?"Retake advised":"Review preview"}</b></div><p>This crop check measures geometric image loss. The dashed box shows recommended head-and-shoulder spacing.</p></div>:null}<button className="primary" onClick={onStart}>Start new camera session <Camera size={19}/></button></section></div></main>;
}

function loadImage(src:string){return new Promise<HTMLImageElement>((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=src})}
async function assess(src:string):Promise<Assessment>{
 const img=await loadImage(src),canvas=document.createElement("canvas"),ctx=canvas.getContext("2d");canvas.width=64;canvas.height=64;ctx?.drawImage(img,0,0,64,64);
 const pixels=ctx?.getImageData(0,0,64,64).data;let total=0;if(pixels)for(let i=0;i<pixels.length;i+=4)total+=(pixels[i]+pixels[i+1]+pixels[i+2])/3;
 const light=pixels?total/(pixels.length/4):128,resolution=img.naturalWidth>=640&&img.naturalHeight>=640,lighting=light>55&&light<225;
 const score=Math.max(45,Math.min(96,58+(resolution?20:0)+(lighting?18:0))),pass=resolution&&lighting;
 return {score,status:pass?"pass":"retake",lighting:lighting?"Good":light<=55?"Too dark":"Too bright",resolution:resolution?"High":"Low",note:pass?"Great result. Your photo is clear and ready to use.":`${resolution?"":"Use a larger photo. "}${lighting?"":"Move to soft, even light and try again."}`.trim()};
}
async function enhancedCopy(src:string){const img=await loadImage(src),c=document.createElement("canvas"),ctx=c.getContext("2d");c.width=img.naturalWidth;c.height=img.naturalHeight;if(!ctx)return src;ctx.filter="brightness(1.05) contrast(1.06) saturate(.96)";ctx.drawImage(img,0,0);return c.toDataURL("image/jpeg",.9)}
async function normalizePhoto(src:string){const img=await loadImage(src),max=1600,scale=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight)),c=document.createElement("canvas"),ctx=c.getContext("2d");c.width=Math.round(img.naturalWidth*scale);c.height=Math.round(img.naturalHeight*scale);if(!ctx)return src;ctx.drawImage(img,0,0,c.width,c.height);return c.toDataURL("image/jpeg",.88)}

export default function Studio(){
 const [view,setView]=useState<View>("profile"),[toast,setToast]=useState(""),[query,setQuery]=useState(""),[count,setCount]=useState<number|null>(null),[cameraStatus,setCameraStatus]=useState<"idle"|"starting"|"live"|"error">("idle"),[cameraError,setCameraError]=useState(""),[photo,setPhoto]=useState<string>(""),[original,setOriginal]=useState<string>(""),[dimensions,setDimensions]=useState({width:0,height:0}),[assessment,setAssessment]=useState<Assessment|null>(null),[checking,setChecking]=useState(false),[enhanced,setEnhanced]=useState(false),[profileOK,setProfileOK]=useState(true),[brandOK,setBrandOK]=useState(true),[gallery,setGallery]=useState<Photo[]>([]);
 const [scanStatus,setScanStatus]=useState<"idle"|"starting"|"live"|"error">("idle"),[scanError,setScanError]=useState(""),[sessionCode,setSessionCode]=useState(""),[sessionAgent,setSessionAgent]=useState<{agentName:string;agentId:string;agentPhoto?:string;rating?:number;date?:string;time?:string}|null>(null);
 const [shotCount,setShotCount]=useState<1|2|3|5>(1),[beautifyOn,setBeautifyOn]=useState(true),[beautify,setBeautify]=useState(35),[shooting,setShooting]=useState(false),[timer,setTimer]=useState<number|null>(null),[shots,setShots]=useState<Array<{id:string;original:string;intensity:number}>>([]),[placement,setPlacement]=useState<"checking"|"ready"|"close"|"far"|"center">("checking");
 const videoRef=useRef<HTMLVideoElement>(null),scannerVideoRef=useRef<HTMLVideoElement>(null),scannerControlsRef=useRef<IScannerControls|null>(null),streamRef=useRef<MediaStream|null>(null),fileRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{try{const saved=localStorage.getItem("ps-gallery");if(saved)setGallery(JSON.parse(saved))}catch{}},[]);
 useEffect(()=>{try{localStorage.setItem("ps-gallery",JSON.stringify(gallery.slice(0,6)))}catch{}},[gallery]);
 useEffect(()=>()=>streamRef.current?.getTracks().forEach(t=>t.stop()),[]);
 useEffect(()=>()=>scannerControlsRef.current?.stop(),[]);
 useEffect(()=>{if(view!=="capture"||cameraStatus!=="live")return;let cancelled=false;const FaceDetectorCtor=(window as unknown as {FaceDetector?:new(o:{fastMode:boolean;maxDetectedFaces:number})=>{detect:(v:HTMLVideoElement)=>Promise<Array<{boundingBox:DOMRectReadOnly}>>}}).FaceDetector;if(!FaceDetectorCtor){setPlacement("checking");return}const detector=new FaceDetectorCtor({fastMode:true,maxDetectedFaces:1});const check=async()=>{const video=videoRef.current;if(!video||video.readyState<2)return;try{const faces=await detector.detect(video);if(cancelled)return;if(!faces.length){setPlacement("center");return}const box=faces[0].boundingBox,headSize=box.height/video.videoHeight,centerX=(box.x+box.width/2)/video.videoWidth,top=box.y/video.videoHeight;if(headSize>.27)setPlacement("close");else if(headSize<.11)setPlacement("far");else if(Math.abs(centerX-.5)>.13||top<.06||top>.3)setPlacement("center");else setPlacement("ready")}catch{if(!cancelled)setPlacement("checking")}};check();const id=window.setInterval(check,500);return()=>{cancelled=true;window.clearInterval(id)}},[view,cameraStatus]);
 useEffect(()=>{const code=new URLSearchParams(location.search).get("session");if(code)loadStudioSession(code)},[]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(""),2600);return()=>clearTimeout(t)},[toast]);
 const go=(v:View)=>{if(v!=="capture")stopCamera();setView(v);window.scrollTo({top:0,behavior:"smooth"})};
 const loadStudioSession=async(raw:string)=>{let code=raw.trim();try{const parsed=new URL(code);code=parsed.searchParams.get("session")||code}catch{}code=decodeURIComponent(code);setScanError("");try{let data:null|{agentName:string;agentId:string;agentPhoto?:string;rating?:number;date?:string;time?:string}=null;const saved=localStorage.getItem(`photostudio-session:${code}`);if(saved)data=JSON.parse(saved);if(!data){const response=await fetch(`/api/studio-sessions?session=${encodeURIComponent(code)}`,{cache:"no-store"});if(!response.ok)throw new Error("Appointment not found");data=await response.json()}scannerControlsRef.current?.stop();setSessionAgent(data);setSessionCode(code);setScanStatus("idle");setView("session");history.replaceState({},"",`/?session=${encodeURIComponent(code)}`);setToast(`${data.agentName} loaded`)}catch{setScanError("Appointment not found. Book in Atlas, then scan the new QR or enter its code.");setScanStatus("error")}};
 const startScanner=async()=>{setScanStatus("starting");setScanError("");try{const reader=new BrowserQRCodeReader();const controls=await reader.decodeFromVideoDevice(undefined,scannerVideoRef.current!,result=>{if(result)loadStudioSession(result.getText())});scannerControlsRef.current=controls;setScanStatus("live")}catch(e){setScanStatus("error");setScanError(e instanceof Error&&e.name==="NotAllowedError"?"Camera permission is off. Allow access, then try again.":"The QR camera could not start. Enter the appointment code below.")}};
 const stopCamera=()=>{streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;setCameraStatus(s=>s==="error"?s:"idle")};
 const startCamera=async()=>{setCameraStatus("starting");setCameraError("");let timedOut=false;try{if(!navigator.mediaDevices?.getUserMedia)throw new Error("Camera access is not supported in this browser.");const request=navigator.mediaDevices.getUserMedia({video:{facingMode:"user",width:{ideal:1280},height:{ideal:1280}},audio:false});request.then(s=>{if(timedOut)s.getTracks().forEach(t=>t.stop())}).catch(()=>{});const timeout=new Promise<never>((_,reject)=>setTimeout(()=>{timedOut=true;reject(new Error("Camera permission timed out. Check the browser camera icon, allow access, then tap Try Again."))},10000));const stream=await Promise.race([request,timeout]);streamRef.current=stream;if(videoRef.current){videoRef.current.srcObject=stream;await videoRef.current.play()}setCameraStatus("live")}catch(e){setCameraStatus("error");setCameraError(e instanceof Error&&e.name==="NotAllowedError"?"Camera permission is off. Allow camera access in your browser, then tap Try Again.":e instanceof Error?e.message:"Camera could not start.")}};
 const reviewPhoto=async(src:string)=>{setChecking(true);try{const img=await loadImage(src);setDimensions({width:img.naturalWidth,height:img.naturalHeight});const normalized=await normalizePhoto(src);setPhoto(normalized);setOriginal(normalized);const result=await assess(normalized);setAssessment(result);setView("review")}catch{setToast("This image could not be opened. Choose a JPG, PNG or WebP file.")}finally{setChecking(false)}};
 const upload=async(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];e.target.value="";if(!file)return;if(!file.type.startsWith("image/")){setToast("Choose an image file: JPG, PNG or WebP.");return}if(file.size>12*1024*1024){setToast("Choose a photo smaller than 12 MB.");return}const reader=new FileReader();reader.onload=()=>typeof reader.result==="string"&&reviewPhoto(reader.result);reader.onerror=()=>setToast("The file could not be read. Try another photo.");reader.readAsDataURL(file)};
 const takePhoto=()=>{if(cameraStatus!=="live"||!videoRef.current){startCamera();return}setCount(3);let n=3;const timer=setInterval(()=>{n-=1;setCount(n);if(n>0)return;clearInterval(timer);const v=videoRef.current!;const c=document.createElement("canvas");c.width=v.videoWidth||960;c.height=v.videoHeight||960;c.getContext("2d")?.drawImage(v,0,0,c.width,c.height);const src=c.toDataURL("image/jpeg",.9);stopCamera();setCount(null);reviewPhoto(src)},700)};
 const waitCountdown=async(seconds:number)=>{for(let value=seconds;value>0;value-=.1){setTimer(Math.max(0,Math.round(value*10)/10));await new Promise(r=>setTimeout(r,100))}};
 const captureCurrent=()=>{const v=videoRef.current!,c=document.createElement("canvas"),ctx=c.getContext("2d")!;c.width=v.videoWidth||1280;c.height=v.videoHeight||1280;const amount=beautifyOn?beautify:0;ctx.filter=`brightness(${1+amount*.0012}) contrast(${1+amount*.0007}) saturate(${1+amount*.00045}) sepia(${amount*.00035})`;ctx.drawImage(v,0,0,c.width,c.height);if(amount){ctx.save();ctx.globalAlpha=Math.min(.32,amount*.0032);ctx.filter=`blur(${Math.max(1,amount*.035)}px) brightness(1.035)`;ctx.drawImage(c,0,0);ctx.restore()}return c.toDataURL("image/jpeg",.92)};
 const shootSequence=async()=>{if(cameraStatus!=="live"){await startCamera();return}setShooting(true);setShots([]);await waitCountdown(15.5);const next=[] as Array<{id:string;original:string;intensity:number}>;for(let i=0;i<shotCount;i++){if(i>0)await waitCountdown(3);next.push({id:crypto.randomUUID(),original:captureCurrent(),intensity:beautifyOn?beautify:0});setShots([...next])}setTimer(null);setShooting(false);stopCamera();setView("batch")};
 const openSessionCamera=()=>{setView("capture");setTimeout(()=>startCamera(),80)};
 const confirm=async()=>{const finalUrl=enhanced?await enhancedCopy(original):original;const item:Photo={id:crypto.randomUUID(),dataUrl:finalUrl,createdAt:new Date().toISOString(),enhanced,profileOK,brandOK,...dimensions};setPhoto(finalUrl);setGallery(g=>[item,...g.filter(x=>x.dataUrl!==finalUrl)].slice(0,6));setView("success")};
 const download=(src:string,name="iqi-professional-portrait.jpg")=>{const a=document.createElement("a");a.href=src;a.download=name;document.body.appendChild(a);a.click();a.remove();setToast("Photo downloaded")};
 const printPhoto=(src:string)=>{const w=window.open("","_blank","noopener,noreferrer");if(!w){setToast("Allow pop-ups to open the print page.");return}w.document.write(`<title>Print IQI Portrait</title><style>body{margin:0;display:grid;place-items:center;min-height:100vh;background:#eee}img{max-width:100%;max-height:100vh;object-fit:contain}@media print{body{background:#fff}}</style><img src="${src}" onload="print()" alt="IQI portrait">`);w.document.close();setToast("Print page opened")};
 const reset=()=>{stopCamera();setPhoto("");setOriginal("");setAssessment(null);setEnhanced(false);setProfileOK(true);setBrandOK(true);setGallery([]);localStorage.removeItem("ps-gallery");setView("profile");setToast("Demo reset")};
 const brandAssets=useMemo(()=>gallery.filter(x=>x.brandOK),[gallery]);
 const filtered=useMemo(()=>brandAssets.filter(()=>"Aisha Rahman".toLowerCase().includes(query.toLowerCase())),[brandAssets,query]);
 const Step=({n,label}:{n:number;label:string})=><div className="steps"><span>Step {n} of 4</span><i><b style={{width:`${n*25}%`}}/></i><span>{label}</span></div>;
 const ActivePhoto=({enhance=false}:{enhance?:boolean})=><PhotoView src={photo||undefined} className={enhance?"enhanced-photo":""}/>;
 if(view==="session"&&sessionAgent)return <SessionProfile agent={sessionAgent} code={sessionCode} onStart={openSessionCamera}/>;
 if(view==="capture"&&sessionAgent){const placementCopy={checking:"Stand inside the guide",ready:"Perfect waist-up framing",close:"Step back a little",far:"Move a little closer",center:"Center your head in the oval"}[placement];return <main className={`studio-camera placement-${placement}`}><video ref={videoRef} autoPlay muted playsInline style={{filter:beautifyOn?`brightness(${1+beautify*.0012}) contrast(${1+beautify*.0007}) saturate(${1+beautify*.00045}) sepia(${beautify*.00035})`:"none"}}/>{beautifyOn?<div className="beauty-preview" style={{backdropFilter:`blur(${beautify*.014}px)`,opacity:.08+beautify*.0015}}/>:null}<div className="camera-top"><button onClick={()=>{stopCamera();setView("session")}}>×</button><div><span>{sessionAgent.agentName}</span><small>Professional waist-up portrait</small></div><b>{shots.length}/{shotCount}</b></div><div className="camera-stage"><div className="ratio-label">4:5 PORTRAIT</div><div className="crop-corners"><i/><i/><i/><i/></div><div className="head-guide"/><div className="waist-guide"><span>WAISTLINE</span></div></div><div className={`placement-status ${placement}`}><i>{placement==="ready"?<Check size={17}/>:<ScanLine size={17}/>}</i><span>{placementCopy}</span></div>{timer!==null?<div className="studio-timer"><div className="countdown-pulse"><strong>{Math.max(1,Math.ceil(timer))}</strong></div><span>{shots.length?"Next portrait":"Hold your pose"}</span></div>:null}<div className="camera-controls"><div className="shot-options"><span>Shots</span>{([1,2,3,5] as const).map(n=><button className={shotCount===n?"active":""} onClick={()=>setShotCount(n)} disabled={shooting} key={n}>{n}</button>)}</div><div className="beauty-control"><button className={beautifyOn?"on":""} onClick={()=>setBeautifyOn(v=>!v)}><Sparkles size={17}/> Smooth {beautifyOn?"On":"Off"}</button><input aria-label="Beautifier intensity" type="range" min="0" max="100" value={beautify} disabled={!beautifyOn||shooting} onChange={e=>setBeautify(+e.target.value)}/><b>{beautify}%</b></div><button className="shutter" onClick={shootSequence} disabled={shooting||cameraStatus!=="live"} aria-label="Start photo sequence"><i/></button></div>{cameraStatus!=="live"?<div className="camera-loading">{cameraStatus==="error"?cameraError:"Starting camera…"}</div>:null}</main>}
 if(view==="batch"&&sessionAgent)return <main className="batch-review"><header><div><span className="eyebrow">SESSION COMPLETE</span><h1>Choose your photos</h1><p>Adjust beautification for each image or remove it.</p></div><button onClick={openSessionCamera}><Camera size={18}/> Take more</button></header><div className="batch-grid">{shots.map((shot,index)=><article key={shot.id}><img src={shot.original} alt={`Captured portrait ${index+1}`} style={{filter:`brightness(${1+shot.intensity*.0015}) contrast(${1+shot.intensity*.001}) saturate(${1-shot.intensity*.0005})`}}/><div><b>Photo {index+1}</b><button onClick={()=>setShots(list=>list.filter(x=>x.id!==shot.id))}><Trash2 size={17}/> Remove</button></div><label><Sparkles size={16}/> Beautifier <input type="range" min="0" max="100" value={shot.intensity} onChange={e=>setShots(list=>list.map(x=>x.id===shot.id?{...x,intensity:+e.target.value}:x))}/><strong>{shot.intensity}%</strong></label></article>)}</div><footer><button className="primary" disabled={!shots.length} onClick={()=>{const first=shots[0];setPhoto(first.original);setOriginal(first.original);setView("select")}}>Continue with {shots.length} photo{shots.length===1?"":"s"} <ArrowRight size={18}/></button></footer></main>;
 return <main className="app-shell"><a className="skip-link" href="#app-content">Skip to content</a><header className="app-bar"><button className="logo" onClick={()=>go("profile")} aria-label="PhotoStudio+ home"><b><i/><i/><i/></b><span><strong>IQI</strong> PhotoStudio<sup>+</sup></span></button><div className="session-state"><i/> Studio ready</div><div className="tools"><button onClick={reset}><RotateCcw size={16}/> Reset Session</button></div></header><nav className="app-nav" aria-label="Main navigation">{nav.map(({id,label,icon:NavIcon})=><button className={view===id?"active":""} onClick={()=>go(id)} key={id}><span aria-hidden="true"><NavIcon size={22}/></span><b>{label}</b></button>)}</nav><div id="app-content" className="app-content">
 {view==="profile"&&<section className="qr-home enter"><div className="qr-intro"><span className="eyebrow">PHOTOSTUDIO+ CHECK-IN</span><h1>Scan your Atlas QR</h1><p>Open your confirmed appointment in Atlas and hold the QR inside the frame.</p><a href="/atlas">Open Atlas profile demo <ArrowRight size={16}/></a></div><div className={`qr-scanner ${scanStatus}`}><video ref={scannerVideoRef} muted playsInline/><div className="scan-shade"/><div className="scan-frame"><i/><i/><i/><i/>{scanStatus==="live"?<span>Scanning…</span>:<QrCode size={54}/>}</div>{scanStatus!=="live"?<button className="scanner-start" onClick={startScanner}><Camera size={19}/>{scanStatus==="starting"?"Starting camera…":"Start QR camera"}</button>:null}</div><div className="manual-checkin"><div><Keyboard size={19}/><span><b>Can’t scan?</b> Enter the appointment code.</span></div><form onSubmit={e=>{e.preventDefault();loadStudioSession(sessionCode)}}><input value={sessionCode} onChange={e=>setSessionCode(e.target.value)} placeholder="PS-IQI-ATLAS-…" aria-label="Appointment code"/><button><ScanLine size={18}/> Load session</button></form>{scanError?<p role="alert">{scanError}</p>:null}</div></section>}
 {view==="capture"&&<section className="dark enter"><Step n={1} label="Add Photo"/><div className="capture"><div><span className="eyebrow pale">CAMERA OR UPLOAD</span><h1>{cameraStatus==="live"?"You’re ready.":"Let’s take your photo."}</h1><p>{cameraStatus==="live"?"Look at the camera, relax your shoulders, then take the photo.":"Start your camera, or choose a photo already on this device."}</p><ul><li><span>1</span> Keep only yourself in the frame</li><li><span>2</span> Use soft light facing you</li></ul>{cameraError?<div className="camera-error" role="alert">{cameraError}</div>:null}<button className="gold" disabled={cameraStatus==="starting"||checking} onClick={takePhoto}><Camera size={19}/>{cameraStatus==="live"?"Take Photo":cameraStatus==="starting"?"Starting Camera…":cameraStatus==="error"?"Try Camera Again":"Start Camera"}</button><button className="upload" onClick={()=>fileRef.current?.click()} disabled={checking}><Upload size={18}/>{checking?"Checking Photo…":"Upload a Photo"}</button><input ref={fileRef} className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" onChange={upload} aria-label="Upload portrait photo"/></div><div className={`viewfinder ${cameraStatus==="live"?"has-video":""}`}><div className="vfhead"><span>BROWSER CAMERA</span><span className={cameraStatus==="live"?"live":""}>● {cameraStatus==="live"?"LIVE":"READY"}</span></div><video ref={videoRef} className="camera-video" autoPlay playsInline muted/><div className="person"><i/><b/></div><div className="oval"/><div className="cross x"/><div className="cross y"/><span className="tip">Line up your eyes here</span><div className="vfmeta"><span>LOCAL</span><span>PRIVATE</span><span>HD</span></div>{count!==null?<div className="count">{count||<Check size={72}/>}</div>:null}</div></div></section>}
 {view==="review"&&assessment&&<section className="flow enter"><Step n={2} label="Photo Check"/><div className="review"><div className="photo-wrap"><ActivePhoto/><span>ON-DEVICE PHOTO CHECK</span></div><div className="result"><span className="eyebrow">PROFESSIONAL READINESS</span><div className={`status ${assessment.status}`}><i>{assessment.status==="pass"?<Check size={19}/>:<HelpCircle size={19}/>}</i>{assessment.status==="pass"?"Ready to Use":"One Quick Retake"}</div><div className="score"><strong>{assessment.score}</strong><span>/ 100<br/>technical readiness</span></div><h2>{assessment.note}</h2><p>This local demo checks image lighting and resolution. It never scores attractiveness.</p><div className="checks"><span>Lighting <b>{assessment.lighting}</b></span><span>Resolution <b>{assessment.resolution}</b></span><span>Image size <b>{dimensions.width} × {dimensions.height}</b></span><span>Privacy <b>On device</b></span></div>{assessment.status==="pass"?<button className="primary" onClick={()=>go("select")}>Choose This Photo <ArrowRight size={18}/></button>:<><button className="primary" onClick={()=>go("capture")}>Try Again</button><button className="link" onClick={()=>fileRef.current?.click()}>Choose Another Photo</button><input ref={fileRef} className="sr-only" type="file" accept="image/*" onChange={upload}/></>}</div></div></section>}
 {view==="select"&&<section className="flow enter"><Step n={3} label="Choose Finish"/><div className="title"><span className="eyebrow">YOUR FINAL PORTRAIT</span><h1>Choose the finish you prefer.</h1><p>Enhancement adjusts light and contrast only. Your original is always kept.</p></div><div className="sheet"><button className={!enhanced?"selected":""} onClick={()=>setEnhanced(false)}><div className="selection-photo"><ActivePhoto/></div><span><b>Original</b><small>Exactly as captured</small></span><i>{!enhanced?<Check size={17}/>:null}</i></button><button className={enhanced?"selected":""} onClick={()=>setEnhanced(true)}><div className="selection-photo"><ActivePhoto enhance/></div><span><b>Light Enhancement</b><small>Balanced light & contrast</small></span><i>{enhanced?<Check size={17}/>:null}</i></button></div><button className="primary center" onClick={()=>go("consent")}>Use {enhanced?"Enhanced":"Original"} Photo <ArrowRight size={18}/></button></section>}
 {view==="consent"&&<section className="flow narrow enter"><Step n={4} label="Permission"/><span className="eyebrow">YOU’RE IN CONTROL</span><h1>Where may IQI use this photo?</h1><p className="lead">Choose each permission separately. You can change your mind later.</p><div className="consents"><label><span><b>My Atlas Profile</b><small>Use this as your professional profile photo.</small></span><input type="checkbox" checked={profileOK} onChange={e=>setProfileOK(e.target.checked)}/><i/></label><label><span><b>IQI Brand Materials</b><small>Allow approved use in posters, social posts and campaigns.</small></span><input type="checkbox" checked={brandOK} onChange={e=>setBrandOK(e.target.checked)}/><i/></label></div><p className="privacy">Brand Gallery access is only enabled when brand permission is on.</p><button className="primary" disabled={!profileOK||!photo} onClick={confirm}>Confirm & Update Profile</button></section>}
 {view==="success"&&<section className="success enter"><div className="tick"><Check size={36}/></div><span className="eyebrow">ATLAS DEMO UPDATED</span><h1>Your portrait is ready.</h1><p>The final image is saved in this browser. {brandOK?"It also appears in the permissioned Brand Asset Gallery.":"It remains private to your profile gallery."}</p><div className="mini"><PhotoView src={photo}/><div><small>IQI Atlas profile</small><b>Aisha Rahman</b><span>● Updated just now</span></div></div><button className="primary" onClick={()=>go("personal")}>View My Gallery <ArrowRight size={18}/></button>{brandOK?<button className="link" onClick={()=>go("brand")}>Open Brand Asset Gallery</button>:null}</section>}
 {view==="personal"&&<section className="gallery photos-page enter"><div className="photos-toolbar"><div><h1>My Photos</h1><span>{gallery.length} {gallery.length===1?"photo":"photos"}</span></div><button className="primary" onClick={()=>go("capture")}><Camera size={18}/> Add Photo</button></div>{gallery.length?<div className="personal-grid">{gallery.map((item,i)=><article className="photo-card" key={item.id}><PhotoView src={item.dataUrl} badge={i===0?"Profile photo":undefined}/><div className="photo-card-info"><div><b>{item.enhanced?"Enhanced":"Original"}</b><span>{new Intl.DateTimeFormat(undefined,{dateStyle:"medium"}).format(new Date(item.createdAt))}</span></div><div className="photo-actions"><button onClick={()=>download(item.dataUrl)} aria-label="Download photo" title="Download"><Download size={18}/><span>Download</span></button><button onClick={()=>printPhoto(item.dataUrl)} aria-label="Print photo" title="Print"><Printer size={18}/><span>Print</span></button></div></div></article>)}</div>:<div className="photos-empty"><span><Images size={28}/></span><h2>No Photos Yet</h2><p>Add a photo to begin.</p><button className="primary" onClick={()=>go("capture")}><Camera size={18}/> Add Photo</button></div>}</section>}
 {view==="brand"&&<section className="gallery enter"><div className="gallery-head"><div><span className="eyebrow">PERMISSIONED LIBRARY</span><h1>Brand Asset Gallery</h1><p>Only portraits with active brand-use permission appear here.</p></div><label className="search">Search Portraits<input name="asset-search" autoComplete="off" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by agent name…"/></label></div><div className="filters"><button><Check size={16}/> All Approved</button><span>{filtered.length} assets</span></div>{filtered.length?<div className="assets">{filtered.map(item=><article key={item.id}><PhotoView src={item.dataUrl} badge="Brand use approved"/><div><small>IQI-{item.id.slice(0,6).toUpperCase()}</small><h3>Aisha Rahman</h3><p>Malaysia · Real Estate Negotiator</p><button onClick={()=>download(item.dataUrl,"iqi-aisha-rahman-high-res.jpg")}><Download size={17}/> Download High-Res</button></div></article>)}</div>:<div className="empty-state"><h2>No approved assets found</h2><p>Approve brand use during the photo flow, or clear your search.</p><button onClick={()=>setQuery("")}>Clear Search</button></div>}</section>}
 {view==="console"&&<section className="console enter"><div className="console-title"><div><span className="eyebrow pale">EVENT STUDIO · STATION 01</span><h1>Studio Operator Console</h1><p>Browser camera and local photo output are available now.</p></div><span>● LOCAL MODE</span></div><div className="devices"><article><i><Camera size={34}/></i><small>CAMERA</small><h2>Browser Camera</h2><b className={cameraStatus==="error"?"offline":"ready"}>● {cameraStatus==="live"?"Live":cameraStatus==="error"?"Needs attention":"Ready"}</b><p>{cameraError||"Phone, webcam or built-in camera"}</p><button onClick={()=>go("capture")}><Camera size={17}/> Open Camera</button></article><article><i><Printer size={34}/></i><small>PHOTO OUTPUT</small><h2>Download & Print</h2><b className="ready">● Ready</b><p>{gallery.length} saved portrait{gallery.length===1?"":"s"}</p><button disabled={!gallery[0]} onClick={()=>gallery[0]&&printPhoto(gallery[0].dataUrl)}><Printer size={17}/> Print Latest</button></article><article><i><CreditCard size={34}/></i><small>PAYMENT</small><h2>Demo Checkout</h2><b className="ready">● Ready</b><p>QR, card and cash remain safe mock adapters.</p><button onClick={()=>setToast("Demo payment completed")}><CreditCard size={17}/> Run Demo Payment</button></article></div><div className="architecture"><div><span className="eyebrow">INTEGRATION-READY</span><h2>Working locally. Ready to connect.</h2><p>Camera, upload, download and print work in-browser. Atlas, DSLR tethering, automated printers and payments remain adapter boundaries for future APIs and a Local Studio Bridge.</p></div><div>Capture <ArrowRight size={17}/> Check <ArrowRight size={17}/> Consent <ArrowRight size={17}/> Gallery</div></div></section>}
 <button className="help" onClick={()=>setToast("Studio staff notified")} aria-label="Call studio staff"><HelpCircle size={19}/><span>Need Help? Call Studio Staff</span></button>{toast?<div className="toast" role="status" aria-live="polite"><Check size={18}/> {toast}</div>:null}
 </div></main>
}
