"use client";

import {ChangeEvent, useEffect, useMemo, useRef, useState} from "react";
import QRCode from "qrcode";
import {BarChart3, Bell, CalendarDays, Camera, Check, ChevronDown, Globe2, Handshake, Headphones, LayoutDashboard, MapPin, Menu, MessageSquare, QrCode, Radar, ShieldCheck, Upload, Users, X} from "lucide-react";
import "./atlas.css";
import "./skeleton-fix.css";

type Metric={name:string;score:number;note:string};
type Rating={score:number;label:string;tone:"good"|"fair"|"low";metrics:Metric[]};
type Agent={id:string;name:string;role:string;office:string;phone:string;email:string;avatar:string;renTag:string};
const fallbackAgent:Agent={id:"71502",name:"Aaron Paul",role:"Negotiator · REN76860",office:"IQI Global · Ipoh, Malaysia",phone:"60126791098",email:"aaronyuva1017@gmail.com",avatar:"",renTag:"REN76860"};

function evaluatePhoto(src:string){return new Promise<Rating>((resolve,reject)=>{const image=new Image();image.crossOrigin="anonymous";image.onload=()=>{try{const s=96,c=document.createElement("canvas"),x=c.getContext("2d",{willReadFrequently:true});c.width=s;c.height=s;if(!x)throw Error();x.drawImage(image,0,0,s,s);const d=x.getImageData(0,0,s,s).data,l:number[]=[];for(let i=0;i<d.length;i+=4)l.push(.2126*d[i]+.7152*d[i+1]+.0722*d[i+2]);const mean=l.reduce((a,b)=>a+b)/l.length,dev=Math.sqrt(l.reduce((a,b)=>a+(b-mean)**2,0)/l.length);let edge=0,n=0;for(let y=1;y<s-1;y++)for(let xx=1;xx<s-1;xx++){const i=y*s+xx;edge+=Math.abs(4*l[i]-l[i-1]-l[i+1]-l[i-s]-l[i+s]);n++}const values=[Math.min(100,Math.round(Math.min(image.naturalWidth,image.naturalHeight)/12)),Math.round(Math.max(0,100-Math.abs(mean-145)*1.35)),Math.round(Math.min(100,dev/52*100)),Math.round(Math.min(100,(edge/n)/42*100)),Math.round(Math.max(0,100-Math.abs(image.naturalWidth/image.naturalHeight-.8)*125)),72],names=["Resolution","Lighting","Contrast","Sharpness","Portrait framing","Face"],notes=[`${image.naturalWidth} × ${image.naturalHeight}px`,mean<90?"Too dark":mean>205?"Too bright":"Balanced exposure",values[2]>60?"Good separation":"Looks flat",values[3]>60?"Clear detail":"May be soft",values[4]>70?"Portrait proportion":"Check crop","Browser visual check"];const metrics=names.map((name,i)=>({name,score:values[i],note:notes[i]})),score=Math.round(values[0]*.2+values[1]*.2+values[2]*.15+values[3]*.2+values[4]*.1+values[5]*.15);resolve({score,label:score>=85?"Studio ready":score>=70?"Good, can improve":"Retake recommended",tone:score>=85?"good":score>=70?"fair":"low",metrics})}catch(e){reject(e)}};image.onerror=reject;image.src=src})}
const initialRating:Rating={score:0,label:"Checking photo…",tone:"fair",metrics:["Resolution","Lighting","Contrast","Sharpness","Portrait framing","Face"].map(name=>({name,score:0,note:"Waiting for image"}))};

export default function AtlasProfile({agentSlug="aaron-paul"}:{agentSlug?:string}){
 const [agent,setAgent]=useState<Agent>(fallbackAgent); const [live,setLive]=useState(false); const [photo,setPhoto]=useState(""); const [rating,setRating]=useState<Rating>(initialRating); const [showAssessment,setShowAssessment]=useState(false); const [booking,setBooking]=useState(false); const [confirmed,setConfirmed]=useState(false); const [qr,setQr]=useState(""); const [qrError,setQrError]=useState(""); const [date,setDate]=useState("2026-08-22"); const [time,setTime]=useState("10:30"); const file=useRef<HTMLInputElement>(null);
 useEffect(()=>{setLive(false);setRating(initialRating);fetch(`/api/atlas-agent?slug=${encodeURIComponent(agentSlug)}`).then(r=>r.ok?r.json():Promise.reject()).then(data=>{const mapped:Agent={id:String(data.id),name:data.display_name||data.full_name,role:[data.designation,data.ren_tag].filter(Boolean).join(" · ")||data.role,office:`IQI Global · ${data.branch_name||data.branch_region_name}, ${data.country}`,phone:data.mobile_contact_number||data.work_contact_number||"Not provided",email:data.email||"Not provided",avatar:`/api/atlas-avatar?slug=${encodeURIComponent(agentSlug)}`,renTag:data.ren_tag||""};setAgent(mapped);setLive(true);setPhoto(mapped.avatar);evaluatePhoto(mapped.avatar).then(setRating).catch(()=>setRating({...initialRating,label:"Could not assess"}))}).catch(()=>{})},[agentSlug]);
 const session=useMemo(()=>`PS-${agent.id}-${date.replaceAll("-","")}-${time.replace(":","")}`,[date,time]);
 useEffect(()=>{if(!confirmed)return;let active=true;const create=async()=>{setQr("");setQrError("");const payload={session,agentId:agent.id,agentName:agent.name,agentPhoto:photo,rating:rating.score,date,time},stored={...payload,createdAt:new Date().toISOString(),status:"confirmed"};localStorage.setItem(`photostudio-session:${session}`,JSON.stringify(stored));try{const response=await fetch("/api/studio-sessions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!response.ok)throw Error();const image=await QRCode.toDataURL(session,{width:360,margin:4,errorCorrectionLevel:"H",color:{dark:"#17221e",light:"#ffffff"}});if(active)setQr(image)}catch{if(active)setQrError("Could not register this QR. Check the demo server and select Try again.")}};create();return()=>{active=false}},[confirmed,session,date,time,agent.id,agent.name,photo,rating.score]);
 const choose=async(e:ChangeEvent<HTMLInputElement>)=>{const selected=e.target.files?.[0];e.target.value="";if(!selected)return;if(!["image/jpeg","image/png","image/webp"].includes(selected.type)){alert("Choose a JPG, PNG or WebP photo.");return}if(selected.size>12*1024*1024){alert("Choose a photo smaller than 12 MB.");return}const reader=new FileReader();reader.onload=async()=>{if(typeof reader.result!=="string")return;setPhoto(reader.result);setRating(initialRating);try{setRating(await evaluatePhoto(reader.result))}catch{alert("This photo could not be assessed. Try another image.")}};reader.onerror=()=>alert("This photo could not be opened.");reader.readAsDataURL(selected)};
 const openStudio=()=>location.href=`/?session=${encodeURIComponent(session)}`;
 return <main className="atlas-app">
  <header className="atlas-top"><button className="menu-toggle" aria-label="Menu"><Menu/></button><div className="atlas-utilities"><Globe2/><MessageSquare/><Headphones/><span className="notice"><Bell/><i>1</i></span><b>{agent.name}</b><span className="user-dot">AP</span></div></header>
  <aside className="atlas-side"><a className="atlas-mark" href="/atlas"><b><i/><i/><i/></b><span>ATLAS<em>Demo profile</em></span></a><div className="side-search">⌕ &nbsp; Search menu</div><small>QUICK LINKS</small><nav><button><LayoutDashboard/><span>Dashboard</span></button><button><Users/><span>Team Hub</span><ChevronDown/></button><button><BarChart3/><span>Insights & Reports</span><ChevronDown/></button><button><Radar/><span>Real Estate Radar</span><ChevronDown/></button><button><Handshake/><span>Engagement Hub</span><ChevronDown/></button><button><CalendarDays/><span>IQI Calendar</span></button><button><Globe2/><span>Global Network</span></button></nav></aside>
  <section className="atlas-content">
   <div className="atlas-page-title"><span><Users/></span><h1>Profile</h1></div><div className="atlas-tabs"><button className="active">Profile</button><button>Digital Signature</button><button>Change Password</button></div>
   <div className="atlas-heading"><div><small>MY PROFILE · {live?"LIVE ATLAS DATA":"OFFLINE FALLBACK"}</small><h1>Professional profile</h1><p>Keep your public agent profile accurate and ready for clients.</p></div><button className="save"><Check size={17}/> {live?"Atlas connected":"Using fallback"}</button></div>
   {rating.score>0&&rating.score<75?<div className={`quality-banner ${!photo?"empty":""}`}><div className="banner-icon"><Camera/></div><div><strong>{!photo?"Your profile needs a professional photo":"Your current photo can be improved"}</strong><span>{!photo?"Add a photo now or reserve a guided PhotoStudio+ session.":`Photo quality is ${rating.score}/100. A studio session can improve lighting, framing and consistency.`}</span></div><button onClick={()=>setBooking(true)}><CalendarDays size={18}/> Book PhotoStudio+</button></div>:null}
   <div className="profile-layout">
    <article className="profile-card"><div className="cover"><span>IQI GLOBAL</span></div><div className="identity"><div className={`agent-photo ${photo?"has-photo":""}`} style={photo?{backgroundImage:`url(${photo})`}:undefined}><span className={`rating-ring ${rating.tone}`}>{rating.score}</span></div><div><h2>{agent.name}</h2><p>{agent.role}</p><span><MapPin size={15}/>{agent.office}</span></div></div><button className="photo-score" onClick={()=>setShowAssessment(true)} aria-label="View full photo assessment"><div><small>PROFESSIONAL PHOTO RATING</small><strong>{rating.score}<span>/100</span></strong></div><div className="score-track"><i style={{width:`${rating.score}%`}}/></div><b className={rating.tone}>{rating.label}</b><p>Click to view assessment details <span>→</span></p></button><div className="atlas-photo-actions"><button type="button" onClick={()=>file.current?.click()}><Upload size={18}/> Upload photo</button><button type="button" className="studio-book" onClick={()=>{setConfirmed(false);setQr("");setQrError("");setBooking(true)}}><CalendarDays size={18}/> Book PhotoStudio+</button><input ref={file} type="file" accept="image/jpeg,image/png,image/webp" onChange={choose}/></div></article>
    <article className="details-card atlas-skeleton" aria-label="Atlas profile modules loading"><div className="skeleton-tabs"><i/><i/><i/><i/></div><div className="skeleton-title"><i/><i/></div><div className="skeleton-grid">{Array.from({length:9},(_,i)=><span key={i}><i/><b/></span>)}</div><div className="skeleton-lines"><i/><i/><i/></div></article>
   </div>
  </section>
  {showAssessment?<div className="booking-backdrop" role="dialog" aria-modal="true" aria-label="Photo assessment"><div className="booking-card assessment-modal"><button className="close" onClick={()=>setShowAssessment(false)} aria-label="Close assessment"><X/></button><small>PHOTO QUALITY</small><h2>{rating.score}/100 · {rating.label}</h2><p>Measured from the current image. Upload a new photo to recalculate.</p><div className="metric-list">{rating.metrics.map(metric=><div className="metric" key={metric.name}><div><b>{metric.name}</b><span>{metric.note}</span><strong>{metric.score}</strong></div><i><b style={{width:`${metric.score}%`}}/></i></div>)}</div><div className="rating-method"><ShieldCheck size={18}/><p><b>Transparent scoring</b><span>Resolution 20% · lighting 20% · contrast 15% · sharpness 20% · framing 10% · face check 15%</span></p></div></div></div>:null}
  {booking?<div className="booking-backdrop" role="dialog" aria-modal="true" aria-label="Book PhotoStudio appointment"><div className="booking-card"><button className="close" onClick={()=>{setBooking(false);setConfirmed(false);setQr("");setQrError("")}} aria-label="Close"><X/></button>{!confirmed?<><span className="modal-icon"><Camera/></span><small>PHOTOSTUDIO+</small><h2>Book your photo session</h2><p>Choose a time, then scan your appointment QR at the studio.</p><div className="booking-fields"><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Time<select value={time} onChange={e=>setTime(e.target.value)}><option>09:30</option><option>10:30</option><option>14:00</option><option>16:30</option></select></label></div><div className="booking-location"><MapPin/><div><b>IQI PhotoStudio+</b><span>Menara IQI, Kuala Lumpur · Level 12</span></div></div><button type="button" className="confirm" onClick={()=>setConfirmed(true)}>Confirm appointment</button></>:<><span className="modal-icon success"><QrCode/></span><small>APPOINTMENT CONFIRMED</small><h2>Your studio QR</h2><p>Scan this QR at PhotoStudio+ to load your profile and begin.</p><div className="qr-wrap">{qr?<img src={qr} alt={`PhotoStudio appointment QR for ${agent.name}`}/>:<span className="qr-loading">Creating QR…</span>}</div><div className="session-code"><small>LOAD SESSION CODE</small><code>{session}</code><span>Enter this code in PhotoStudio+ if scanning is unavailable.</span></div>{qrError?<p className="qr-error">{qrError}</p>:null}<div className="appointment-meta"><div><small>AGENT</small><b>{agent.name}</b></div><div><small>DATE & TIME</small><b>{date} · {time}</b></div></div><button type="button" className="confirm" disabled={!qr} onClick={openStudio}><QrCode size={18}/> Open PhotoStudio+ demo</button></>}</div></div>:null}
 </main>
}
